name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: cargo run --release
    - name: Check Directory Contents
      run: | 
        ls
        ls ./docs
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs/*
        git commit -m "generated"
        git push
